## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway export_igw {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-06T21:11:50.049Z"
  }
  display_name = "igw"
  enabled      = "true"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_vcn_webserver.id
}
resource oci_core_internet_gateway export_DemoIGW {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:45:32.326Z"
  }
  display_name = "DemoIGW"
  enabled      = "true"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_CLI-Demo-VCN.id
}
resource oci_core_internet_gateway export_Internet-Gateway-CLI-Demo {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:51.909Z"
  }
  display_name = "Internet Gateway-CLI-Demo"
  enabled      = "true"
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  vcn_id = oci_core_vcn.export_CLI-Demo.id
}
resource oci_core_public_ip export_IP-for-NAT-gateway-ocid1-natgateway-oc1-iad-aaaaaaaax3flrdkkytnbrisqtiogshp4ydyiorkthy22qfrcuvsbcmw4ip7q {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:53.032Z"
  }
  display_name = "IP for NAT gateway: ocid1.natgateway.oc1.iad.aaaaaaaax3flrdkkytnbrisqtiogshp4ydyiorkthy22qfrcuvsbcmw4ip7q"
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  lifetime = "EPHEMERAL"
  #private_ip_id = <<Optional value not found in discovery>>
}
resource oci_core_service_gateway export_Service-Gateway-CLI-Demo {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:52.596Z"
  }
  display_name = "Service Gateway-CLI-Demo"
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }
  vcn_id = oci_core_vcn.export_CLI-Demo.id
}
resource oci_core_subnet export_subnet2-AD2 {
  availability_domain = "kDFU:US-ASHBURN-AD-2"
  cidr_block          = "10.10.20.0/24"
  compartment_id      = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-06T21:11:51.693Z"
  }
  dhcp_options_id = oci_core_vcn.export_vcn_webserver.default_dhcp_options_id
  display_name    = "subnet2-AD2"
  #dns_label = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_route_table.export_rt1.id
  security_list_ids = [
    oci_core_security_list.export_sl-loadbalancer.id,
  ]
  vcn_id = oci_core_vcn.export_vcn_webserver.id
}
resource oci_core_subnet export_subnet1-AD1 {
  availability_domain = "kDFU:US-ASHBURN-AD-1"
  cidr_block          = "10.10.10.0/24"
  compartment_id      = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-06T21:11:51.644Z"
  }
  dhcp_options_id = oci_core_vcn.export_vcn_webserver.default_dhcp_options_id
  display_name    = "subnet1-AD1"
  #dns_label = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_route_table.export_rt1.id
  security_list_ids = [
    oci_core_security_list.export_sl-loadbalancer.id,
  ]
  vcn_id = oci_core_vcn.export_vcn_webserver.id
}
resource oci_core_subnet export_subnet20200805154352 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "192.168.10.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:43:52.143Z"
  }
  dhcp_options_id = oci_core_vcn.export_CLI-Demo-VCN.default_dhcp_options_id
  display_name    = "subnet20200805154352"
  #dns_label = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_CLI-Demo-VCN.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_CLI-Demo-VCN.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_CLI-Demo-VCN.id
}
resource oci_core_subnet export_Private-Subnet-CLI-Demo {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:51.873Z"
  }
  dhcp_options_id = oci_core_vcn.export_CLI-Demo.default_dhcp_options_id
  display_name    = "Private Subnet-CLI-Demo"
  dns_label       = "sub08051520441"
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_Route-Table-for-Private-Subnet-CLI-Demo.id
  security_list_ids = [
    oci_core_security_list.export_Security-List-for-Private-Subnet-CLI-Demo.id,
  ]
  vcn_id = oci_core_vcn.export_CLI-Demo.id
}
resource oci_core_subnet export_Public-Subnet-CLI-Demo {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:51.745Z"
  }
  dhcp_options_id = oci_core_vcn.export_CLI-Demo.default_dhcp_options_id
  display_name    = "Public Subnet-CLI-Demo"
  dns_label       = "sub08051520440"
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_CLI-Demo.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_CLI-Demo.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_CLI-Demo.id
}
resource oci_core_vcn export_vcn_webserver {
  cidr_block     = "10.10.0.0/16"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-06T21:11:43.698Z"
  }
  display_name = "vcn_webserver"
  dns_label    = "vcn"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  #is_ipv6enabled = <<Optional value not found in discovery>>
}
resource oci_core_vcn export_CLI-Demo-VCN {
  cidr_block     = "192.168.0.0/16"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:39:08.332Z"
  }
  display_name = "CLI-Demo-VCN"
  dns_label    = "clidemovcn"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  #is_ipv6enabled = <<Optional value not found in discovery>>
}
resource oci_core_vcn export_CLI-Demo {
  cidr_block     = "10.0.0.0/16"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:50.393Z"
  }
  display_name = "CLI-Demo"
  dns_label    = "clidemo"
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  #is_ipv6enabled = <<Optional value not found in discovery>>
}
resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-vcn_webserver {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-06T21:11:43.698Z"
  }
  display_name = "Default DHCP Options for vcn_webserver"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn_webserver.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcn.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}
resource oci_core_route_table export_rt1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-06T21:11:51.021Z"
  }
  display_name = "rt1"
  freeform_tags = {
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_igw.id
  }
  vcn_id = oci_core_vcn.export_vcn_webserver.id
}
resource oci_core_default_route_table export_Default-Route-Table-for-vcn_webserver {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-06T21:11:43.698Z"
  }
  display_name = "Default Route Table for vcn_webserver"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn_webserver.default_route_table_id
}
resource oci_core_security_list export_sl-loadbalancer {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-06T21:11:50.370Z"
  }
  display_name = "sl-loadbalancer"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "0"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "8"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_vcn_webserver.id
}
resource oci_core_default_security_list export_Default-Security-List-for-vcn_webserver {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-06T21:11:43.698Z"
  }
  display_name = "Default Security List for vcn_webserver"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.10.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_vcn_webserver.default_security_list_id
}
resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-CLI-Demo-VCN {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:39:08.332Z"
  }
  display_name = "Default DHCP Options for CLI-Demo-VCN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_CLI-Demo-VCN.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "clidemovcn.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}
resource oci_core_default_route_table export_Default-Route-Table-for-CLI-Demo-VCN {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:39:08.332Z"
  }
  display_name = "Default Route Table for CLI-Demo-VCN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_CLI-Demo-VCN.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_DemoIGW.id
  }
}
resource oci_core_default_security_list export_Default-Security-List-for-CLI-Demo-VCN {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:39:08.332Z"
  }
  display_name = "Default Security List for CLI-Demo-VCN"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "192.168.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_CLI-Demo-VCN.default_security_list_id
}
resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-CLI-Demo {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:50.393Z"
  }
  display_name = "Default DHCP Options for CLI-Demo"
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  manage_default_resource_id = oci_core_vcn.export_CLI-Demo.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "clidemo.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}
resource oci_core_nat_gateway export_NAT-Gateway-CLI-Demo {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:51.925Z"
  }
  display_name = "NAT Gateway-CLI-Demo"
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  vcn_id = oci_core_vcn.export_CLI-Demo.id
}
resource oci_core_route_table export_Route-Table-for-Private-Subnet-CLI-Demo {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:51.878Z"
  }
  display_name = "Route Table for Private Subnet-CLI-Demo"
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_NAT-Gateway-CLI-Demo.id
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-iad-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_Service-Gateway-CLI-Demo.id
  }
  vcn_id = oci_core_vcn.export_CLI-Demo.id
}
resource oci_core_default_route_table export_Default-Route-Table-for-CLI-Demo {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:50.393Z"
  }
  display_name = "Default Route Table for CLI-Demo"
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  manage_default_resource_id = oci_core_vcn.export_CLI-Demo.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-CLI-Demo.id
  }
}
resource oci_core_security_list export_Security-List-for-Private-Subnet-CLI-Demo {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:51.937Z"
  }
  display_name = "Security List for Private Subnet-CLI-Demo"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_CLI-Demo.id
}
resource oci_core_default_security_list export_Default-Security-List-for-CLI-Demo {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "gustavo.watanabe@gmail.com"
    "Oracle-Tags.CreatedOn" = "2020-08-05T15:20:50.393Z"
  }
  display_name = "Default Security List for CLI-Demo"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2020-08-05T15:20:31"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_CLI-Demo.default_security_list_id
}
